<?php
	if ($_SERVER['REQUEST_METHOD'] === 'GET') { exit; }

	require_once 'standardDefinitions.php';

	function generateConfiguration($privilegeLevel,$theIP,$theNetmask,$clientPrivateKey,$allowedIPs)
	{
		global $theServerIP;
		global $standardServerParameters;

		$localServerParameters=$standardServerParameters[$privilegeLevel];


		$configurationTemplate = array(
			0 => '# Generated by FMI\'s WireguardLDAP',
			1 => '[Interface]',
			2 => 'Address = '.$theIP.'/'.$theNetmask,
			3 => 'PrivateKey = '.$clientPrivateKey,
			4 => '[Peer]',
			5 => 'PublicKey = '.$localServerParameters['pubKey'],
			6 => 'AllowedIPs = '.$allowedIPs,
			7 => 'Endpoint = '.$theServerIP.':'.$localServerParameters['port'],
			8 => 'PersistentKeepalive = 25'
		);

		$configurationResult = "";
		foreach ($configurationTemplate as $configurationLine)
		{
			$configurationResult = $configurationResult.$configurationLine."\n";
		}
		return $configurationResult;
	}
?>
