<?php
	if ($_SERVER['REQUEST_METHOD'] === 'GET') { exit; }

	require_once 'standardDefinitions.php';

	function generateConfiguration($privilegeLevel,$theIP,$theNetmask,$clientPrivateKey)
	{
		global $theServerIP;
		global $standardServerParameters;

		$localServerParameters=$standardServerParameters[$privilegeLevel];


		$configurationTemplate = array(
			0 => '# Generated by FMI\'s WireguardLDAP',
			1 => '# Who to blame if it doesn\'t work: alexandru.kiraly@ubbcluj.ro',
			2 => '[Interface]',
			3 => 'Address = '.$theIP.'/'.$theNetmask,
			4 => 'PrivateKey = '.$clientPrivateKey,
			5 => 'DNS = 172.30.0.1',
			6 => '[Peer]',
			7 => 'PublicKey = '.$localServerParameters['pubKey'],
			8 => 'AllowedIPs = '.$localServerParameters['allowedIPs'],
			9 => 'Endpoint = '.$theServerIP.':'.$localServerParameters['port'],
			10 => 'PersistentKeepalive = 25'
		);

		$configurationResult = "";
		foreach ($configurationTemplate as $configurationLine)
		{
			$configurationResult = $configurationResult.$configurationLine."\n";
		}
		return $configurationResult;
	}

